# Generated by Django 5.1.11 on 2025-08-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0240_jira_instance_password_help_text_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='use_v3_labels',
            field=models.BooleanField(default=True, help_text='Whether to use the labels associated with v3.', verbose_name='Use V3 Labels'),
        ),
    ]
