# Generated by Django 5.1.11 on 2025-08-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0240_jira_instance_password_help_text_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='labels_version',
            field=models.CharField(choices=[('v2', 'V2'), ('v3', 'V3')], default='v2', help_text='The version of labels to use.', max_length=2, verbose_name='Labels Version'),
        ),
    ]
