# Generated by Django 5.1.11 on 2025-08-15 16:30
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0242_file_upload_cleanup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_settings',
            name='time_zone',
       ),
    ]
